title:              八宝粥的博客
SEOTitle:           八宝粥的博客 | wangzzleo
email:              wangzzleo@gmail.com
description:        说什么都不合适
baseurl:            ""
author:             wangzz
url:                "https://www.wangzzleo.top"

# Social Profiles
twitter_username:   wangzzleo
github_username:    wangzzleo
facebook_username:  wangzzleo
jianshu_username:   7eac69299be6

# Google Analytics
google_analytics:   'G-K202D30ENX'            # Format: UA-xxxxxx-xx
google_ads:         ca-pub-6504830816842759


# Build settings
highlighter:        rouge
markdown_ext:       "markdown,mkdown,mkdn,mkd,md"
markdown:           kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  # syntax_highlighter: coderay
  # syntax_highlighter_opts:
  #   line_numbers: table
  #   bold_every: 5
  # hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
paginate:           10
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
